#!/usr/bin/env python3
# Copyright (C) 2024 Igalia S.L.
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 2.1 of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with this program; if not, write to the
# Free Software Foundation, Inc., 51 Franklin St, Fifth Floor,
# Boston, MA 02110-1301, USA.

import os
import sys

source_dir = os.path.normpath(os.path.join(os.path.dirname(__file__), "..", ".."))

sys.path.insert(0, os.path.join(source_dir, "Tools", "flatpak"))
import flatpak

import argparse

def flatpak_install_sdk(args):
    flatpak.install_sdk()

def flatpak_update_dependencies(args):
    flatpak.update_dependencies();

def flatpak_run(args):
    flatpak.run(args.command)

def flatpak_enter(args):
    flatpak.run(["bash"])

if __name__ == "__main__":
    parser = argparse.ArgumentParser(prog="flatpak")
    subparsers = parser.add_subparsers()

    parser_install_sdk = subparsers.add_parser("install-sdk")
    parser_install_sdk.set_defaults(func=flatpak_install_sdk)

    parser_update_dependencies = subparsers.add_parser("update-dependencies")
    parser_update_dependencies.set_defaults(func=flatpak_update_dependencies)

    parser_run = subparsers.add_parser("run")
    parser_run.add_argument("command", nargs=argparse.REMAINDER)
    parser_run.set_defaults(func=flatpak_run)

    parser_enter = subparsers.add_parser("enter")
    parser_enter.set_defaults(func=flatpak_enter)

    args = parser.parse_args()
    args.func(args)
